### PR TITLE
Update with a whole new Assimp

### PR DESCRIPTION
**Pull request by fluffyfreak**
Does exactly what it says. Latest Assimp from Git.

ping @robn in case this breaks the nightly builds etc

### CODE REVIEW

**Comment by walterar** [comment]
This PR is for the master of Pioneer or pioneer-thirdparty?

**Comment by fluffyfreak** [comment]
Both

**Comment by walterar** [comment]
I ask because I was testing the new assimp 3.2 and have problems with some models gernot.

**Comment by walterar** [comment]
Testing in Linux, it seems that there are no problems.
Is there any reason not to use static library?

**Comment by fluffyfreak** [comment]
That's kind of the problem, there's trouble getting it to link statically using MXE.
ALso for vs2015 builds everything is DLL instead of LIB, just because some libraries aren't available as LIB's on Windows :(

**Comment by walterar** [comment]
I see the version 3.2 creates a libassimp.dll.a when version 3.0.1264 created a libassimp.a
The new library is only 4.7 Mb when before it was 13.8 Mb, and not incorporated into the pioneer.exe
In Linux, apparently, no problems. But it increased 49.7 Mb to  67.2 Mb
I normally use gcc 4.8.1, but for assimp 3.2, I had to install 5.2

I think we're in trouble :)  :(

**Comment by robn** [comment]
I'm ready to do a test build against assimp 3.2. I have a working MXE, but thirdparty is required for the Linux builds. I will merge this in the next hour or two (with some supporting configure.ac/Makefile.in changes) unless there's any objections.

**Comment by fluffyfreak** [comment]
@walterar we can discuss models and what needs fixing on the SSC forum, I'll start a conversation over there. Don't panic, it's minor stuff :)

**Comment by walterar** [comment]
@fluffyfreak I do not get scared, I'm terrified. :))

@robn Something happened with the packaging of Linux 64. The file is very large (504.5 MB).
I think you should improve the salary to your robots. ;)

**Pull request merged**
