### PR TITLE
Allow building and running in windows with visual studio 2019

### PR DESCRIPTION
**Pull request by JonBooth78**
Unfortunately, visual studio uses different, non compatible implementations of stl things, like std:sstring between debug and release configurations.  This mean that the libassimp library also needs to be built in a debug mode so the main pioneer executable can also be run in debug mode without crashing.

### CODE REVIEW

**Comment by Web-eWorks** [comment]
CC @fluffyfreak for windows setup (admittedly CMake-based); this looks good to my (untrained) eyes.

**Comment by fluffyfreak** [comment]
It looks good to me, I would like to see less manual copying of files but 🤷 sometimes, what can you do. If those parts can be automated, or fixed to be unnecessary, _in the future_ then that would be a nice fix to have.

This PR however is good to merge @Web-eWorks 👍 

I know I can do merges but I've bene out of the loop so long that I don't want to be rude!

**Review by fluffyfreak — APPROVED** [review]
Does this also work for vs2022?
Approved either way as it meets the scope of the PR

**Comment by Web-eWorks** [comment]
As far as I can tell, this PR involves no more copying than the current build process does for rebuilding libassimp et. al., so it looks good to me.

**Pull request merged**
